/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SmokingLog = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'cigarettesCount' : IDL.Nat,
  'totalSpent' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({
  'pricePerCigarette' : IDL.Float64,
  'notificationsEnabled' : IDL.Bool,
  'dailyLimitGoal' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLog' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [SmokingLog], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLog' : IDL.Func([IDL.Nat], [SmokingLog], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(SmokingLog)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SmokingLog = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'cigarettesCount' : IDL.Nat,
    'totalSpent' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({
    'pricePerCigarette' : IDL.Float64,
    'notificationsEnabled' : IDL.Bool,
    'dailyLimitGoal' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLog' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [SmokingLog], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLog' : IDL.Func([IDL.Nat], [SmokingLog], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(SmokingLog)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };