/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SmokingLog {
  'id' : bigint,
  'date' : string,
  'pricePerUnit' : number,
  'cigarettesCount' : bigint,
  'totalSpent' : number,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'pricePerCigarette' : number,
  'notificationsEnabled' : boolean,
  'dailyLimitGoal' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLog' : ActorMethod<[string, bigint, number], SmokingLog>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLog' : ActorMethod<[bigint], SmokingLog>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLogs' : ActorMethod<[], Array<SmokingLog>>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];